# Dev database
version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: microboard-db
      POSTGRES_USER: microboard
      POSTGRES_PASSWORD: super-password
    volumes:
      - microboard-postgres-dev:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # Nginx for development.
  # All requests starting with '/api' will be passed to the backend, all other requests will be passed to the frontend.
  # Nginx is not used in the production server. The frontend will be compiled into static files that will be served by the backend.
  nginx:
    image: nginx:1.25.0-alpine
    network_mode: host
    volumes:
      - ./nginx-conf-dev:/etc/nginx/conf.d:ro

volumes:
  microboard-postgres-dev:
