# Dev database
version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: microboard-db
      POSTGRES_USER: microboard
      POSTGRES_PASSWORD: super-password
    volumes:
      - microboard-postgres-dev:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  microboard-postgres-dev:
